spring.datasource.url=jdbc:postgresql://dpg-d6kkuingi27c73bfi55g-a.frankfurt-postgres.render.com:5432/todoapp_x2y1
spring.datasource.username=admin
spring.datasource.password=XrqweLH0WPQgE1GHZ8G4aVB6QGSjCkJi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}